<?php
/**
 * SIAX SMSS - Advance Fee Report (Print View)
 */
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
require_login();

$settings = all_settings($conn);
$school_name = $settings['school_name'] ?? 'SIAX SMSS';
$school_logo = $settings['school_logo'] ?? '';

// Selection logic (same as main page)
$sel_class_id = (int)($_GET['class_id'] ?? 0);
$sel_class_name = $_GET['class_name'] ?? '';
$show_adv_only = isset($_GET['adv_only']) && $_GET['adv_only'] == 1;

$where = "s.status='Active'";
if ($sel_class_id) {
    $where .= " AND s.class_id = $sel_class_id";
} elseif ($sel_class_name) {
    $where .= " AND c.name = '" . $conn->real_escape_string($sel_class_name) . "'";
}
if ($show_adv_only) {
    $where .= " AND s.advance_balance > 0";
}

$students_q = $conn->query("
    SELECT s.*, c.name as class_name, c.section 
    FROM students s 
    LEFT JOIN classes c ON s.class_id = c.id 
    WHERE $where 
    ORDER BY (s.roll_no+0), s.name
");
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Advance Fee Report - <?= date('d M Y') ?></title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #fff; color: #000; padding: 40px; }
        
        .print-header { display: flex; align-items: center; justify-content: center; margin-bottom: 30px; border-bottom: 3px solid #1a5276; padding-bottom: 20px; position: relative; }
        .logo { width: 100px; height: 100px; position: absolute; left: 0; top: 0; }
        .logo img { width: 100%; height: 100%; object-fit: contain; }
        .school-info { text-align: center; }
        .school-info h1 { font-size: 26px; font-weight: 800; text-transform: uppercase; margin-bottom: 5px; color: #1a5276; }
        .school-info p { font-size: 13px; color: #444; margin: 2px 0; }

        .report-title { text-align: center; font-size: 20px; font-weight: 700; text-transform: uppercase; margin: 20px 0; text-decoration: underline; }
        
        .meta-bar { background: #f2f2f2; border: 1px solid #ccc; padding: 10px 15px; display: flex; justify-content: space-between; font-size: 13px; font-weight: 600; margin-bottom: 20px; }

        .data-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .data-table th { background: #1a5276; color: #fff; border: 1px solid #000; padding: 10px; text-align: left; font-size: 13px; }
        .data-table td { border: 1px solid #ccc; padding: 8px 10px; font-size: 12px; }
        .data-table tr:nth-child(even) { background: #f9f9f9; }

        .footer-sig { margin-top: 50px; display: flex; justify-content: space-between; }
        .sig-box { border-top: 1px solid #000; padding-top: 5px; min-width: 180px; text-align: center; font-size: 13px; font-weight: 600; }

        .no-print { margin-bottom: 20px; text-align: right; }
        .btn { padding: 8px 20px; border-radius: 4px; font-weight: 600; cursor: pointer; border: none; font-size: 14px; }
        .btn-print { background: #1a5276; color: #fff; }

        @media print {
            .no-print { display: none; }
            body { padding: 20px; }
            .data-table th { background: #eee !important; color: #000 !important; -webkit-print-color-adjust: exact; }
        }
    </style>
</head>
<body>

    <div class="no-print">
        <button class="btn btn-print" onclick="window.print()">Print Report</button>
    </div>

    <div class="print-header">
        <div class="logo">
            <?php if($school_logo): ?>
                <img src="<?= BASE_URL ?>uploads/<?= htmlspecialchars($school_logo) ?>" alt="Logo">
            <?php else: ?>
                <div style="width:100%; height:100%; background:#1a5276; color:#fff; display:flex; align-items:center; justify-content:center; border-radius:50%; font-size:40px; font-weight:800;"><?= strtoupper(substr($school_name,0,1)) ?></div>
            <?php endif; ?>
        </div>
        <div class="school-info">
            <h1><?= htmlspecialchars($school_name) ?></h1>
            <p><?= htmlspecialchars($settings['school_address'] ?? '') ?></p>
            <p>Phone: <?= htmlspecialchars($settings['school_phone'] ?? '') ?> | <?= htmlspecialchars($settings['school_email'] ?? '') ?></p>
        </div>
    </div>

    <div class="report-title">Advance Fee Detail Report</div>

    <div class="meta-bar">
        <span>Selection: <?= $sel_class_id ? 'Class ID: '.$sel_class_id : ($sel_class_name ?: 'All Classes') ?></span>
        <span>Date: <?= date('d M Y') ?></span>
        <span>Generated By: <?= htmlspecialchars(current_user()['full_name'] ?? 'Admin') ?></span>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Reg#</th>
                <th>Roll No</th>
                <th>Student Name</th>
                <th>Father Name</th>
                <th>Class</th>
                <th>Section</th>
                <th>Advance Balance</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($students_q && $students_q->num_rows > 0): 
                $i = 1; $total_adv = 0;
                while($s = $students_q->fetch_assoc()): 
                    $total_adv += $s['advance_balance'];
            ?>
                <tr>
                    <td><?= $i++ ?></td>
                    <td><?= htmlspecialchars($s['admission_no']) ?></td>
                    <td><?= htmlspecialchars($s['roll_no'] ?? '-') ?></td>
                    <td><strong><?= htmlspecialchars($s['name']) ?></strong></td>
                    <td><?= htmlspecialchars($s['father_name'] ?? '-') ?></td>
                    <td><?= htmlspecialchars($s['class_name']) ?></td>
                    <td><?= htmlspecialchars($s['section']) ?></td>
                    <td style="font-weight: 700; text-align: right;"><?= number_format($s['advance_balance'], 2) ?></td>
                </tr>
            <?php endwhile; ?>
                <tr style="background: #eee; font-weight: 800;">
                    <td colspan="7" style="text-align: right;">GRAND TOTAL:</td>
                    <td style="text-align: right;"><?= number_format($total_adv, 2) ?></td>
                </tr>
            <?php else: ?>
                <tr><td colspan="8" style="text-align: center; padding: 20px;">No records found.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="footer-sig">
        <div class="sig-box">Accountant Signature</div>
        <div class="sig-box">Principal Signature</div>
    </div>

</body>
</html>




